// store/programs/fakeData.ts

import { ProgramDay, Exercise, Program, UserWorkoutPlanProgress } from '@/store/programs/types';

// Sample user plan progress
const sampleUserProgress: UserWorkoutPlanProgress = {
    UserId: 'user1',
    WorkoutPlanId: 'plan1',
    CurrentDay: '22',
    StartDate: '2024-07-01',
    LastActivityDate: '2024-07-05',
    Week: 4,
    Day: 1,
};

// Define sample exercises
const sampleExercises: Exercise[] = [
    {
        ExerciseId: 'ex-1',
        ExerciseName: 'Barbell Squat',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Glutes'], Secondary: ['Hips'] },
        InstructionsDetailed:
            '1. Stand with your feet shoulder-width apart. 2. Position the barbell on your shoulders. 3. Lower your body into a squat until your thighs are parallel to the floor. 4. Push through your heels to return to the starting position.',
        QuickTip: 'Use a 3 second down, 1 second hold, 1 second up tempo',
        VideoUrl: 'https://example.com/videos/barbell-squat.mp4',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        Reps: 5,
        WeightInstructions: 'Use 90% of ORM',
    },
    {
        ExerciseId: 'ex-2',
        ExerciseName: 'Dumbbell Bench Press',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Chest'], Secondary: ['Triceps'] },
        InstructionsDetailed:
            '1. Lie on a bench with a dumbbell in each hand. 2. Push the dumbbells up until your arms are fully extended. 3. Lower the dumbbells until your elbows are at a 90-degree angle. 4. Push the dumbbells back up to the starting position.',
        QuickTip: 'Keep your elbows slightly bent at the top of the movement',
        VideoUrl: 'https://example.com/videos/dumbbell-bench-press.mp4',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        Reps: 5,
        WeightInstructions: 'Use 90% of ORM',
    },
    {
        ExerciseId: 'ex-3',
        ExerciseName: 'Pull-Up',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Back'], Secondary: ['Biceps'] },
        InstructionsDetailed:
            '1. Grab the pull-up bar with an overhand grip. 2. Hang from the bar with your arms fully extended. 3. Pull yourself up until your chin is over the bar. 4. Lower yourself back down to the starting position.',
        QuickTip: 'Engage your shoulder blades before pulling up',
        VideoUrl: 'https://example.com/videos/pull-up.mp4',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        Reps: 5,
        WeightInstructions: 'Use 90% of ORM',
    },
];

// Define sample program days
const sampleProgramDays: ProgramDay[] = [
    {
        WorkoutPlanId: 'plan1',
        WorkoutDayId: '22',
        WorkoutDayTitle: 'Full Body',
        RestDay: false,
        Exercises: sampleExercises,
        Notes: 'Welcome to Day 1! Today, we’ll focus on strength training.',
        PhotoUrl: 'https://images.pexels.com/photos/3253501/pexels-photo-3253501.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-07-01',
        LastModified: '2024-07-12',
        Time: 60,
        MuscleGroups: ['Back', 'Chest'],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Barbell', 'Dumbbells', 'Cable Machine'],
        Week: 4,
        Day: 1,
    },
    {
        WorkoutPlanId: 'plan1',
        WorkoutDayId: '23',
        WorkoutDayTitle: 'Upper Body A',
        RestDay: false,
        Exercises: sampleExercises,
        Notes: 'Day 2 is focused on cardio and endurance.',
        PhotoUrl: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg',
        CreationDate: '2024-07-02',
        LastModified: '2024-07-12',
        Time: 45,
        MuscleGroups: ['Legs', 'Arms'],
        EquipmentCategory: 'Basic Equipment',
        Equipment: ['Treadmill', 'Jump Rope'],
        Week: 4,
        Day: 2,
    },
    {
        WorkoutPlanId: 'plan1',
        WorkoutDayId: '24',
        WorkoutDayTitle: 'Lower Body B',
        RestDay: true,
        Exercises: [],
        Notes: 'Rest day. Focus on recovery and stretching.',
        PhotoUrl: 'https://images.pexels.com/photos/1552252/pexels-photo-1552252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-07-03',
        LastModified: '2024-07-12',
        Time: 30,
        MuscleGroups: ['Chest', 'Shoulders'],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Barbell', 'Dumbbells', 'Cable Machine'],
        Week: 4,
        Day: 3,
    },
    {
        WorkoutPlanId: 'plan1',
        WorkoutDayId: '25',
        WorkoutDayTitle: 'Upper Body B',
        RestDay: false,
        Exercises: sampleExercises,
        Notes: 'Back to strength training with new exercises.',
        PhotoUrl: 'https://images.pexels.com/photos/2105493/pexels-photo-2105493.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2g',
        CreationDate: '2024-07-04',
        LastModified: '2024-07-12',
        Time: 60,
        MuscleGroups: ['Chest', 'Shoulders'],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Barbell', 'Dumbbells', 'Cable Machine'],
        Week: 4,
        Day: 4,
    },
];

const mockPrograms: Program[] = [
    {
        WorkoutPlanId: 'plan1',
        WorkoutPlanName: 'Lean Machine Challenge',
        TrainerId: 'trainer123',
        ProgramLength: 6,
        Description: 'A comprehensive 6-week challenge to build strength and endurance.',
        Level: 'All Levels',
        Type: 'Strength',
        Goal: 'Fat loss',
        CreationDate: '2024-07-01',
        LastModified: '2024-07-12',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/lean_machine_challenge.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'We’ll ramp up onto the program by starting with lower weights and volume' },
            { Title: 'Weeks 3-5', Description: 'Start to feel the difference in your body. Feel faster, stronger, and lighter on your feet' },
            { Title: 'Week 6', Description: 'We’ll de-load this week and focus on muscle recovery - setting you up for a solid base to start your next plan' },
        ],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Dumbbells', 'Barbell', 'Cable Machine'],
        Frequency: '4x / week',
        DesignedFor: 'At the gym, for all levels: beginner or expert',
    },
    {
        WorkoutPlanId: 'plan2',
        WorkoutPlanName: "Beginner's Yoga Flow",
        TrainerId: 'trainer124',
        ProgramLength: 8,
        Description: 'An 8-week introduction to yoga for beginners focusing on flexibility and relaxation.',
        Level: 'Beginner',
        Type: 'Yoga',
        Goal: 'Flexibility',
        CreationDate: '2024-06-01',
        LastModified: '2024-06-15',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/beginners_yoga_flow.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'Introduction to basic yoga poses and breathing techniques' },
            { Title: 'Weeks 3-5', Description: 'Building strength and flexibility with intermediate poses' },
            { Title: 'Weeks 6-8', Description: 'Advanced poses and combined flow sequences for relaxation' },
        ],
        EquipmentCategory: 'Basic Equipment',
        Equipment: ['Yoga Mat', 'Block', 'Strap'],
        Frequency: '3x / week',
        DesignedFor: 'At home or at the studio, ideal for beginners',
    },
    {
        WorkoutPlanId: 'plan3',
        WorkoutPlanName: 'Advanced HIIT Series',
        TrainerId: 'trainer125',
        ProgramLength: 6,
        Description: 'A 6-week high-intensity interval training program designed for advanced athletes.',
        Level: 'Advanced',
        Type: 'HIIT',
        Goal: 'Cardio and Strength',
        CreationDate: '2024-08-01',
        LastModified: '2024-08-10',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/advanced_hiit_series.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'High-intensity interval training focusing on strength and conditioning' },
            { Title: 'Weeks 3-4', Description: 'Increased intensity with added plyometric exercises' },
            { Title: 'Weeks 5-6', Description: 'Advanced HIIT techniques and combination workouts for peak performance' },
        ],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Dumbbells', 'Kettlebells', 'Medicine Ball'],
        Frequency: '5x / week',
        DesignedFor: 'Advanced athletes looking for high-intensity workouts',
    },
];

export { sampleProgramDays, mockPrograms, sampleUserProgress };
