// store/programs/mockData.ts

import { ProgramDay, Exercise, Program, UserProgramProgress } from '@/types/types';

// Sample user program progress
const sampleUserProgress: UserProgramProgress = {
    UserId: 'user1',
    ProgramId: 'program1',
    CurrentDay: '22',
    StartDate: '2024-07-01',
    LastActivityDate: '2024-07-05',
    Week: '4',
    Day: '1',
};

// Define sample exercises
const sampleExercises: Exercise[] = [
    {
        ExerciseId: 'ex-1',
        ExerciseName: 'Barbell Squat',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Glutes'], Secondary: ['Hips'] },
        InstructionsDetailed: [
            'Stand with your feet shoulder-width apart.',
            'Position the barbell on your shoulders.',
            'Lower your body into a squat until your thighs are parallel to the floor.',
            'Push through your heels to return to the starting position.',
        ],
        QuickTip: 'Use a 3 second down, 1 second hold, 1 second up tempo',
        VideoUrl: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        BannerUrl: 'https://images.pexels.com/photos/371049/pexels-photo-371049.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        RepsUpper: 6,
        RepsLower: 4,
        Rest: '90s',
        WeightInstructions: '90% of your One Rep Max (1RM)',
    },
    {
        ExerciseId: 'ex-2',
        ExerciseName: 'Dumbbell Bench Press',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Chest'], Secondary: ['Triceps'] },
        InstructionsDetailed: [
            'Stand with your feet shoulder-width apart.',
            'Position the barbell on your shoulders.',
            'Lower your body into a squat until your thighs are parallel to the floor.',
            'Push through your heels to return to the starting position.',
        ],
        QuickTip: 'Keep your elbows slightly bent at the top of the movement',
        VideoUrl: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        BannerUrl: 'https://images.pexels.com/photos/371049/pexels-photo-371049.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        RepsUpper: 6,
        RepsLower: 4,
        Rest: '90s',
        WeightInstructions: '90% of your One Rep Max (1RM)',
    },
    {
        ExerciseId: 'ex-3',
        ExerciseName: 'Pull-Up',
        Category: 'Strength',
        MuscleGroups: { Primary: ['Back'], Secondary: ['Biceps'] },
        InstructionsDetailed: [
            'Stand with your feet shoulder-width apart.',
            'Position the barbell on your shoulders.',
            'Lower your body into a squat until your thighs are parallel to the floor.',
            'Push through your heels to return to the starting position.',
        ],
        QuickTip: 'Engage your shoulder blades before pulling up',
        VideoUrl: 'https://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
        BannerUrl: 'https://images.pexels.com/photos/371049/pexels-photo-371049.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-08-22T12:00:00Z',
        LastModified: '2024-08-22T12:00:00Z',
        Archived: false,
        Sets: 2,
        RepsUpper: 6,
        RepsLower: 4,
        Rest: '90s',
        WeightInstructions: '90% of your One Rep Max (1RM)',
    },
];

// Define sample program days
const sampleProgramDays: ProgramDay[] = [
    {
        ProgramId: 'program1',
        DayId: '22',
        DayTitle: 'Full Body',
        RestDay: false,
        Exercises: sampleExercises,
        PhotoUrl: 'https://images.pexels.com/photos/3253501/pexels-photo-3253501.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-07-01',
        LastModified: '2024-07-12',
        Time: 60,
        MuscleGroups: ['Back', 'Chest'],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Barbell', 'Dumbbells', 'Cable Machine'],
        Week: '4',
        Day: '1',
    },
    {
        ProgramId: 'program1',
        DayId: '23',
        DayTitle: 'Upper Body A',
        RestDay: false,
        Exercises: sampleExercises,
        PhotoUrl: 'https://images.pexels.com/photos/1886487/pexels-photo-1886487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-07-02',
        LastModified: '2024-07-12',
        Time: 45,
        MuscleGroups: ['Legs', 'Arms'],
        EquipmentCategory: 'Basic Equipment',
        Equipment: ['Treadmill', 'Jump Rope'],
        Week: '4',
        Day: '2',
    },
    {
        ProgramId: 'program1',
        DayId: '24',
        DayTitle: 'Lower Body B',
        RestDay: false,
        Exercises: sampleExercises,
        PhotoUrl: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg',
        CreationDate: '2024-07-03',
        LastModified: '2024-07-12',
        Time: 60,
        MuscleGroups: ['Chest', 'Shoulders'],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Barbell', 'Dumbbells', 'Cable Machine'],
        Week: '4',
        Day: '3',
    },
    {
        ProgramId: 'program1',
        DayId: '25',
        DayTitle: 'Rest Day',
        RestDay: true,
        Exercises: [],
        PhotoUrl:
            'https://images.pexels.com/photos/27302737/pexels-photo-27302737/free-photo-of-a-woman-in-blue-and-white-is-doing-a-squat.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        CreationDate: '2024-07-04',
        LastModified: '2024-07-12',
        Time: 0,
        MuscleGroups: [],
        EquipmentCategory: 'None',
        Equipment: [],
        Week: '4',
        Day: '4',
    },
];

const mockPrograms: Program[] = [
    {
        ProgramId: 'program1',
        ProgramName: 'Lean Machine Challenge',
        TrainerId: 'trainer123',
        Weeks: 6,
        Days: 40,
        Description: 'A comprehensive 6-week challenge to build strength and endurance.',
        Level: 'All Levels',
        Type: 'Strength',
        Goal: 'Fat loss',
        CreationDate: '2024-07-01',
        LastModified: '2024-07-12',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/lean_machine_challenge.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'We’ll ramp up onto the program by starting with lower weights and volume' },
            { Title: 'Weeks 3-5', Description: 'Start to feel the difference in your body. Feel faster, stronger, and lighter on your feet' },
            {
                Title: 'Week 6',
                Description: 'We’ll de-load this week and focus on muscle recovery - setting you up for a solid base to start your next program',
            },
        ],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Dumbbells', 'Barbell', 'Cable Machine'],
        Frequency: '4x / week',
        DesignedFor: 'At the gym, for all levels: beginner or expert',
    },
    {
        ProgramId: 'program2',
        ProgramName: "Beginner's Yoga Flow",
        TrainerId: 'trainer124',
        Weeks: 8,
        Days: 56,
        Description: 'An 8-week introduction to yoga for beginners focusing on flexibility and relaxation.',
        Level: 'Beginner',
        Type: 'Yoga',
        Goal: 'Flexibility',
        CreationDate: '2024-06-01',
        LastModified: '2024-06-15',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/beginners_yoga_flow.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'Introduction to basic yoga poses and breathing techniques' },
            { Title: 'Weeks 3-5', Description: 'Building strength and flexibility with intermediate poses' },
            { Title: 'Weeks 6-8', Description: 'Advanced poses and combined flow sequences for relaxation' },
        ],
        EquipmentCategory: 'Basic Equipment',
        Equipment: ['Yoga Mat', 'Block', 'Strap'],
        Frequency: '3x / week',
        DesignedFor: 'At home or at the studio, ideal for beginners',
    },
    {
        ProgramId: 'program3',
        ProgramName: 'Advanced HIIT Series',
        TrainerId: 'trainer125',
        Weeks: 6,
        Days: 42,
        Description: 'A 6-week high-intensity interval training program designed for advanced athletes.',
        Level: 'Advanced',
        Type: 'HIIT',
        Goal: 'Cardio and Strength',
        CreationDate: '2024-08-01',
        LastModified: '2024-08-10',
        PhotoUrl: 'https://s3.amazonaws.com/fitnessapp/images/advanced_hiit_series.jpg',
        Archived: false,
        CalendarOverview: [
            { Title: 'Weeks 1-2', Description: 'High-intensity interval training focusing on strength and conditioning' },
            { Title: 'Weeks 3-4', Description: 'Increased intensity with added plyometric exercises' },
            { Title: 'Weeks 5-6', Description: 'Advanced HIIT techniques and combination workouts for peak performance' },
        ],
        EquipmentCategory: 'Full Gym',
        Equipment: ['Dumbbells', 'Kettlebells', 'Medicine Ball'],
        Frequency: '5x / week',
        DesignedFor: 'Advanced athletes looking for high-intensity workouts',
    },
];

export { sampleProgramDays, mockPrograms, sampleUserProgress };
